name: nene-deploy

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DEPLOY_TOKEN: ${DEPLOY_TOKEN}

    ports:
      - "8000:8000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - shared

    
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped

    env_file:
      - .env

    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}

    depends_on:
      - webhook

    networks:
      - shared


networks:
  shared:
    external: true
    name: shared
